# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000000
SAVEHIST=10000000
setopt extendedglob
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/tatsuya/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

setopt share_history

autoload -U promptinit
promptinit
prompt gentoo

alias 'ls=ls --color=auto'
